<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Reset Password</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.css">
    <style type="text/css">
        body{ font: 14px sans-serif; }
        .wrapper{ width: 350px; padding: 20px; }
    </style>
</head>
<body>
<div class="wrapper">
    <h2>Update Full name</h2>
    <form action="<?php echo htmlspecialchars($_SERVER["PHP_SELF"]); ?>" method="post">
        <div class="form-group <?php echo (!empty($fullName_err)) ? 'has-error' : ''; ?>">
            <label>New Full Name</label>
            <?php foreach($oldFullName as $name) : ?>
            <input type="text" name="fullName" class="form-control" value="<?php echo $name; ?>">
            <span class="help-block"><?php echo $fullName_err; ?></span>
            <?php endforeach; ?>
        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Submit">
            <a class="btn btn-link" href="welcome.php">Cancel</a>
        </div>
    </form>
</div>
</body>
</html>